var BBT = {
en: {
  nav_arch: 'Architecture', nav_colors: 'Colors', nav_typo: 'Typography', nav_domains: 'Domains',
  nav_langs: 'Languages', nav_components: 'Components', nav_issues: 'Issues', nav_guidelines: 'Guidelines',
  hero_eyebrow: '// LABS67 Concern Brand Book',
  hero_title: 'Brand<br><em>System</em>',
  hero_sub: 'Complete design standards, color systems, typography rules, component specifications, and guidelines for all LABS67 concern domains. For developers, designers, and partners.',
  hero_domains: 'Domains', hero_subbrands: 'Sub-Brands', hero_languages: 'Languages', hero_fonts: 'Font Families', hero_system: 'System',
  toc_label: '// Contents', toc_title: 'Brand Book Structure',
  toc_arch: 'Brand Architecture', toc_arch_desc: 'Parent brand, sub-brands, hierarchy and relationships',
  toc_colors: 'Color System', toc_colors_desc: 'Primary, secondary, accent palettes per brand',
  toc_typo: 'Typography', toc_typo_desc: 'Font families, sizes, weights, usage rules',
  toc_domains: 'Domain Audit', toc_domains_desc: 'Current state of all 6 domains',
  toc_langs: 'Language System', toc_langs_desc: '11 languages, flags, i18n standards',
  toc_components: 'UI Components', toc_components_desc: 'Buttons, forms, cards, navigation specs',
  toc_issues: 'Inconsistencies', toc_issues_desc: 'Found problems and required fixes',
  toc_guidelines: 'Developer Guidelines', toc_guidelines_desc: 'Rules for developers implementing changes',
  s01_label: '// 01 Brand Architecture', s01_title: 'Concern Structure',
  s01_sub: 'LABS67 is a technology concern (holding company) with 5 operational sub-brands. Each sub-brand has its own visual identity but must follow the parent system.',
  arch_parent_desc: 'Technology Concern // Parent Brand',
  arch_svt: 'Aesthetic Dentistry', arch_scyra: 'Edge AI System', arch_academi: 'Clinical Education',
  arch_trade: 'MedTech Products', arch_franchise: 'Scaling & Partners',
  s02_label: '// 02 Color System', s02_title: 'Color Palette',
  s02_sub: 'The LABS67 color system defines a shared foundation with brand-specific accent colors. All sub-brands share the same neutrals and gold primary.',
  s02_global: 'Global Foundation',
  s03_label: '// 03 Typography', s03_title: 'Font System',
  s03_sub: 'Four font families serve different roles across the ecosystem. Each sub-brand uses a specific combination.',
  s04_label: '// 04 Domain Audit', s04_title: 'Current State',
  s04_sub: 'Snapshot of all 6 LABS67 domains as of March 23, 2026. Each domain analyzed for design consistency, language support, and standards compliance.',
  s05_label: '// 05 Language System', s05_title: '11 Languages Standard',
  s05_sub: 'ALL LABS67 domains must support 11 languages. Belarusian is the default language. Special flag rules apply for BY and RU.',
  s06_label: '// 06 UI Components', s06_title: 'Component Specifications',
  s06_sub: 'Standard UI component specifications for developers. All measurements in pixels, all durations in milliseconds.',
  s07_label: '// 07 Inconsistencies Found', s07_title: 'Audit Issues',
  s07_sub: 'Problems discovered during the domain audit that need to be fixed for brand consistency.',
  issue_langs_title: 'Language count mismatch', issue_langs_desc: 'All domains now have full language coverage. svyatlitsa: 11 langs. academi67/trade/franchise: 12 langs each.',
  issue_chat_title: 'svyatlitsa.com has no chat widget', issue_chat_desc: 'Chat widget has been added to svyatlitsa.com. Patients can now interact with SCYRA AI directly from the clinic website.',
  s08_label: '// 08 Developer Guidelines', s08_title: 'Implementation Rules',
  s08_sub: 'Mandatory rules for any developer working on LABS67 ecosystem sites. Follow these before making any changes.',
  footer_version: 'Brand Book v1.0 // Generated 2026-03-23',
  footer_copy: '&copy; 2026 LABS67 Concern // Confidential'
},
be: {
  nav_arch: 'Архiтэктура', nav_colors: 'Колеры', nav_typo: 'Тыпаграфiка', nav_domains: 'Дамены',
  nav_langs: 'Мовы', nav_components: 'Кампаненты', nav_issues: 'Праблемы', nav_guidelines: 'Рэкамендацыi',
  hero_eyebrow: '// Брэнд-бук канцэрна LABS67',
  hero_title: 'Брэнд-<br><em>сiстэма</em>',
  hero_sub: 'Поўныя стандарты дызайну, каляровыя сiстэмы, правiлы тыпаграфiкi, спецыфiкацыi кампанентаў i рэкамендацыi для ўсiх даменаў канцэрна LABS67. Для распрацоўшчыкаў, дызайнераў i партнёраў.',
  hero_domains: 'Дамены', hero_subbrands: 'Суб-брэнды', hero_languages: 'Мовы', hero_fonts: 'Сям\'i шрыфтоў', hero_system: 'Сiстэма',
  toc_label: '// Змест', toc_title: 'Структура брэнд-бука',
  toc_arch: 'Архiтэктура брэнда', toc_arch_desc: 'Галоўны брэнд, суб-брэнды, iерархiя i ўзаемасувязi',
  toc_colors: 'Каляровая сiстэма', toc_colors_desc: 'Асноўныя, другасныя, акцэнтныя палiтры для кожнага брэнда',
  toc_typo: 'Тыпаграфiка', toc_typo_desc: 'Сям\'i шрыфтоў, памеры, вагi, правiлы выкарыстання',
  toc_domains: 'Аўдыт даменаў', toc_domains_desc: 'Бягучы стан усiх 6 даменаў',
  toc_langs: 'Моўная сiстэма', toc_langs_desc: '11 моў, сцягi, стандарты i18n',
  toc_components: 'UI-кампаненты', toc_components_desc: 'Кнопкi, формы, карткi, спецыфiкацыi навiгацыi',
  toc_issues: 'Неадпаведнасцi', toc_issues_desc: 'Знойдзеныя праблемы i неабходныя выпраўленнi',
  toc_guidelines: 'Рэкамендацыi распрацоўшчыкам', toc_guidelines_desc: 'Правiлы для распрацоўшчыкаў пры ўнясеннi змяненняў',
  s01_label: '// 01 Архiтэктура брэнда', s01_title: 'Структура канцэрна',
  s01_sub: 'LABS67 — тэхналагiчны канцэрн (холдынгавая кампанiя) з 5 аперацыйнымi суб-брэндамi. Кожны суб-брэнд мае ўласную вiзуальную iдэнтычнасць, але павiнен адпавядаць бацькоўскай сiстэме.',
  arch_parent_desc: 'Тэхналагiчны канцэрн // Галоўны брэнд',
  arch_svt: 'Эстэтычная стаматалогiя', arch_scyra: 'Edge AI сiстэма', arch_academi: 'Клiнiчная адукацыя',
  arch_trade: 'MedTech прадукты', arch_franchise: 'Маштабаванне i партнёры',
  s02_label: '// 02 Каляровая сiстэма', s02_title: 'Каляровая палiтра',
  s02_sub: 'Каляровая сiстэма LABS67 вызначае агульную аснову з акцэнтнымi колерамi для кожнага брэнда. Усе суб-брэнды выкарыстоўваюць аднолькавыя нейтральныя тоны i залатую асноўную.',
  s02_global: 'Глабальная аснова',
  s03_label: '// 03 Тыпаграфiка', s03_title: 'Сiстэма шрыфтоў',
  s03_sub: 'Чатыры сям\'i шрыфтоў выконваюць розныя ролi ў экасiстэме. Кожны суб-брэнд выкарыстоўвае пэўную камбiнацыю.',
  s04_label: '// 04 Аўдыт даменаў', s04_title: 'Бягучы стан',
  s04_sub: 'Знiмак усiх 6 даменаў LABS67 на 23 сакавiка 2026. Кожны дамен прааналiзаваны на адпаведнасць дызайну, моўную падтрымку i стандарты.',
  s05_label: '// 05 Моўная сiстэма', s05_title: 'Стандарт 11 моў',
  s05_sub: 'УСЕ дамены LABS67 павiнны падтрымлiваць 11 моў. Беларуская — мова па змаўчаннi. Спецыяльныя правiлы сцягоў для BY i RU.',
  s06_label: '// 06 UI-кампаненты', s06_title: 'Спецыфiкацыi кампанентаў',
  s06_sub: 'Стандартныя спецыфiкацыi UI-кампанентаў для распрацоўшчыкаў. Усе вымярэннi ў пiкселях, усе працягласцi ў мiлiсекундах.',
  s07_label: '// 07 Знойдзеныя неадпаведнасцi', s07_title: 'Праблемы аўдыту',
  s07_sub: 'Праблемы, выяўленыя падчас аўдыту даменаў, якiя трэба выправiць для адпаведнасцi брэнду.',
  issue_langs_title: 'Неадпаведнасць колькасцi моў', issue_langs_desc: 'Усе дамены цяпер маюць поўнае моўнае пакрыццё. svyatlitsa: 11 моў. academi67/trade/franchise: 12 моў кожны.',
  issue_chat_title: 'svyatlitsa.com без чат-вiджэта', issue_chat_desc: 'Чат-вiджэт дададзены на svyatlitsa.com. Пацыенты цяпер могуць узаемадзейнiчаць з SCYRA AI непасрэдна з сайта клiнiкi.',
  s08_label: '// 08 Рэкамендацыi распрацоўшчыкам', s08_title: 'Правiлы рэалiзацыi',
  s08_sub: 'Абавязковыя правiлы для любога распрацоўшчыка, якi працуе з сайтамi экасiстэмы LABS67. Выконвайце iх перад унясеннем любых змяненняў.',
  footer_version: 'Брэнд-бук v1.0 // Створана 2026-03-23',
  footer_copy: '&copy; 2026 Канцэрн LABS67 // Канфiдэнцыйна'
},
uk: {
  nav_arch: 'Архiтектура', nav_colors: 'Кольори', nav_typo: 'Типографiка', nav_domains: 'Домени',
  nav_langs: 'Мови', nav_components: 'Компоненти', nav_issues: 'Проблеми', nav_guidelines: 'Рекомендацiї',
  hero_eyebrow: '// Брендбук концерну LABS67',
  hero_title: 'Бренд-<br><em>система</em>',
  hero_sub: 'Повнi стандарти дизайну, колiрнi системи, правила типографiки, специфiкацiї компонентiв та рекомендацiї для всiх доменiв концерну LABS67. Для розробникiв, дизайнерiв та партнерiв.',
  hero_domains: 'Домени', hero_subbrands: 'Суб-бренди', hero_languages: 'Мови', hero_fonts: 'Сiмейства шрифтiв', hero_system: 'Система',
  toc_label: '// Змiст', toc_title: 'Структура брендбуку',
  toc_arch: 'Архiтектура бренду', toc_arch_desc: 'Головний бренд, суб-бренди, iєрархiя та взаємозв\'язки',
  toc_colors: 'Колiрна система', toc_colors_desc: 'Основнi, другоряднi, акцентнi палiтри для кожного бренду',
  toc_typo: 'Типографiка', toc_typo_desc: 'Сiмейства шрифтiв, розмiри, ваги, правила використання',
  toc_domains: 'Аудит доменiв', toc_domains_desc: 'Поточний стан усiх 6 доменiв',
  toc_langs: 'Мовна система', toc_langs_desc: '11 мов, прапори, стандарти i18n',
  toc_components: 'UI-компоненти', toc_components_desc: 'Кнопки, форми, картки, специфiкацiї навiгацiї',
  toc_issues: 'Невiдповiдностi', toc_issues_desc: 'Знайденi проблеми та необхiднi виправлення',
  toc_guidelines: 'Рекомендацiї розробникам', toc_guidelines_desc: 'Правила для розробникiв при внесеннi змiн',
  s01_label: '// 01 Архiтектура бренду', s01_title: 'Структура концерну',
  s01_sub: 'LABS67 — технологiчний концерн (холдингова компанiя) з 5 операцiйними суб-брендами. Кожен суб-бренд має власну вiзуальну iдентичнiсть, але повинен вiдповiдати батькiвськiй системi.',
  arch_parent_desc: 'Технологiчний концерн // Головний бренд',
  arch_svt: 'Естетична стоматологiя', arch_scyra: 'Edge AI система', arch_academi: 'Клiнiчна освiта',
  arch_trade: 'MedTech продукти', arch_franchise: 'Масштабування та партнери',
  s02_label: '// 02 Колiрна система', s02_title: 'Колiрна палiтра',
  s02_sub: 'Колiрна система LABS67 визначає спiльну основу з акцентними кольорами для кожного бренду. Всi суб-бренди використовують однаковi нейтральнi тони та золотий основний.',
  s02_global: 'Глобальна основа',
  s03_label: '// 03 Типографiка', s03_title: 'Система шрифтiв',
  s03_sub: 'Чотири сiмейства шрифтiв виконують рiзнi ролi в екосистемi. Кожен суб-бренд використовує певну комбiнацiю.',
  s04_label: '// 04 Аудит доменiв', s04_title: 'Поточний стан',
  s04_sub: 'Знiмок усiх 6 доменiв LABS67 станом на 23 березня 2026. Кожен домен проаналiзовано на вiдповiднiсть дизайну, мовну пiдтримку та стандарти.',
  s05_label: '// 05 Мовна система', s05_title: 'Стандарт 11 мов',
  s05_sub: 'УСI домени LABS67 повиннi пiдтримувати 11 мов. Бiлоруська — мова за замовчуванням. Спецiальнi правила прапорiв для BY та RU.',
  s06_label: '// 06 UI-компоненти', s06_title: 'Специфiкацiї компонентiв',
  s06_sub: 'Стандартнi специфiкацiї UI-компонентiв для розробникiв. Усi вимiрювання в пiкселях, усi тривалостi в мiлiсекундах.',
  s07_label: '// 07 Знайденi невiдповiдностi', s07_title: 'Проблеми аудиту',
  s07_sub: 'Проблеми, виявленi пiд час аудиту доменiв, якi потрiбно виправити для вiдповiдностi бренду.',
  issue_langs_title: 'Невiдповiднiсть кiлькостi мов', issue_langs_desc: 'Усi домени тепер мають повне мовне покриття. svyatlitsa: 11 мов. academi67/trade/franchise: 12 мов кожен.',
  issue_chat_title: 'svyatlitsa.com без чат-вiджета', issue_chat_desc: 'Чат-вiджет додано на svyatlitsa.com. Пацiєнти тепер можуть взаємодiяти з SCYRA AI безпосередньо з сайту клiнiки.',
  s08_label: '// 08 Рекомендацiї розробникам', s08_title: 'Правила реалiзацiї',
  s08_sub: 'Обов\'язковi правила для будь-якого розробника, який працює з сайтами екосистеми LABS67. Дотримуйтесь їх перед внесенням будь-яких змiн.',
  footer_version: 'Брендбук v1.0 // Створено 2026-03-23',
  footer_copy: '&copy; 2026 Концерн LABS67 // Конфiденцiйно'
},
ru: {
  nav_arch: 'Архитектура', nav_colors: 'Цвета', nav_typo: 'Типографика', nav_domains: 'Домены',
  nav_langs: 'Языки', nav_components: 'Компоненты', nav_issues: 'Проблемы', nav_guidelines: 'Рекомендации',
  hero_eyebrow: '// Брендбук концерна LABS67',
  hero_title: 'Бренд-<br><em>система</em>',
  hero_sub: 'Полные стандарты дизайна, цветовые системы, правила типографики, спецификации компонентов и рекомендации для всех доменов концерна LABS67. Для разработчиков, дизайнеров и партнёров.',
  hero_domains: 'Домены', hero_subbrands: 'Суб-бренды', hero_languages: 'Языки', hero_fonts: 'Семейства шрифтов', hero_system: 'Система',
  toc_label: '// Содержание', toc_title: 'Структура брендбука',
  toc_arch: 'Архитектура бренда', toc_arch_desc: 'Головной бренд, суб-бренды, иерархия и взаимосвязи',
  toc_colors: 'Цветовая система', toc_colors_desc: 'Основные, вторичные, акцентные палитры для каждого бренда',
  toc_typo: 'Типографика', toc_typo_desc: 'Семейства шрифтов, размеры, начертания, правила использования',
  toc_domains: 'Аудит доменов', toc_domains_desc: 'Текущее состояние всех 6 доменов',
  toc_langs: 'Языковая система', toc_langs_desc: '11 языков, флаги, стандарты i18n',
  toc_components: 'UI-компоненты', toc_components_desc: 'Кнопки, формы, карточки, спецификации навигации',
  toc_issues: 'Несоответствия', toc_issues_desc: 'Найденные проблемы и необходимые исправления',
  toc_guidelines: 'Рекомендации разработчикам', toc_guidelines_desc: 'Правила для разработчиков при внесении изменений',
  s01_label: '// 01 Архитектура бренда', s01_title: 'Структура концерна',
  s01_sub: 'LABS67 — технологический концерн (холдинговая компания) с 5 операционными суб-брендами. Каждый суб-бренд имеет собственную визуальную идентичность, но должен соответствовать родительской системе.',
  arch_parent_desc: 'Технологический концерн // Головной бренд',
  arch_svt: 'Эстетическая стоматология', arch_scyra: 'Edge AI система', arch_academi: 'Клиническое образование',
  arch_trade: 'MedTech продукты', arch_franchise: 'Масштабирование и партнёры',
  s02_label: '// 02 Цветовая система', s02_title: 'Цветовая палитра',
  s02_sub: 'Цветовая система LABS67 определяет общую основу с акцентными цветами для каждого бренда. Все суб-бренды используют одинаковые нейтральные тона и золотой основной.',
  s02_global: 'Глобальная основа',
  s03_label: '// 03 Типографика', s03_title: 'Система шрифтов',
  s03_sub: 'Четыре семейства шрифтов выполняют различные роли в экосистеме. Каждый суб-бренд использует определённую комбинацию.',
  s04_label: '// 04 Аудит доменов', s04_title: 'Текущее состояние',
  s04_sub: 'Снимок всех 6 доменов LABS67 на 23 марта 2026. Каждый домен проанализирован на соответствие дизайну, языковую поддержку и стандарты.',
  s05_label: '// 05 Языковая система', s05_title: 'Стандарт 11 языков',
  s05_sub: 'ВСЕ домены LABS67 должны поддерживать 11 языков. Белорусский — язык по умолчанию. Специальные правила флагов для BY и RU.',
  s06_label: '// 06 UI-компоненты', s06_title: 'Спецификации компонентов',
  s06_sub: 'Стандартные спецификации UI-компонентов для разработчиков. Все измерения в пикселях, все длительности в миллисекундах.',
  s07_label: '// 07 Найденные несоответствия', s07_title: 'Проблемы аудита',
  s07_sub: 'Проблемы, обнаруженные при аудите доменов, которые необходимо исправить для соответствия бренду.',
  issue_langs_title: 'Несоответствие количества языков', issue_langs_desc: 'Все домены теперь имеют полное языковое покрытие. svyatlitsa: 11 языков. academi67/trade/franchise: 12 языков каждый.',
  issue_chat_title: 'svyatlitsa.com без чат-виджета', issue_chat_desc: 'Чат-виджет добавлен на svyatlitsa.com. Пациенты теперь могут взаимодействовать с SCYRA AI прямо с сайта клиники.',
  s08_label: '// 08 Рекомендации разработчикам', s08_title: 'Правила реализации',
  s08_sub: 'Обязательные правила для любого разработчика, работающего с сайтами экосистемы LABS67. Соблюдайте их перед внесением любых изменений.',
  footer_version: 'Брендбук v1.0 // Создан 2026-03-23',
  footer_copy: '&copy; 2026 Концерн LABS67 // Конфиденциально'
},
de: {
  nav_arch: 'Architektur', nav_colors: 'Farben', nav_typo: 'Typografie', nav_domains: 'Domains',
  nav_langs: 'Sprachen', nav_components: 'Komponenten', nav_issues: 'Probleme', nav_guidelines: 'Richtlinien',
  hero_eyebrow: '// LABS67 Konzern Brand Book',
  hero_title: 'Marken-<br><em>System</em>',
  hero_sub: 'Vollstaendige Designstandards, Farbsysteme, Typografieregeln, Komponentenspezifikationen und Richtlinien fuer alle Domains des LABS67-Konzerns. Fuer Entwickler, Designer und Partner.',
  hero_domains: 'Domains', hero_subbrands: 'Sub-Marken', hero_languages: 'Sprachen', hero_fonts: 'Schriftfamilien', hero_system: 'System',
  toc_label: '// Inhalt', toc_title: 'Brand-Book-Struktur',
  toc_arch: 'Markenarchitektur', toc_arch_desc: 'Hauptmarke, Sub-Marken, Hierarchie und Beziehungen',
  toc_colors: 'Farbsystem', toc_colors_desc: 'Primaere, sekundaere, Akzentpaletten pro Marke',
  toc_typo: 'Typografie', toc_typo_desc: 'Schriftfamilien, Groessen, Gewichte, Nutzungsregeln',
  toc_domains: 'Domain-Audit', toc_domains_desc: 'Aktueller Stand aller 6 Domains',
  toc_langs: 'Sprachsystem', toc_langs_desc: '11 Sprachen, Flaggen, i18n-Standards',
  toc_components: 'UI-Komponenten', toc_components_desc: 'Buttons, Formulare, Karten, Navigationsspezifikationen',
  toc_issues: 'Inkonsistenzen', toc_issues_desc: 'Gefundene Probleme und erforderliche Korrekturen',
  toc_guidelines: 'Entwicklerrichtlinien', toc_guidelines_desc: 'Regeln fuer Entwickler bei Aenderungen',
  s01_label: '// 01 Markenarchitektur', s01_title: 'Konzernstruktur',
  s01_sub: 'LABS67 ist ein Technologiekonzern (Holdinggesellschaft) mit 5 operativen Sub-Marken. Jede Sub-Marke hat eine eigene visuelle Identitaet, muss aber dem uebergeordneten System folgen.',
  arch_parent_desc: 'Technologiekonzern // Hauptmarke',
  arch_svt: 'Aesthetische Zahnmedizin', arch_scyra: 'Edge-AI-System', arch_academi: 'Klinische Ausbildung',
  arch_trade: 'MedTech-Produkte', arch_franchise: 'Skalierung & Partner',
  s02_label: '// 02 Farbsystem', s02_title: 'Farbpalette',
  s02_sub: 'Das LABS67-Farbsystem definiert eine gemeinsame Grundlage mit markenspezifischen Akzentfarben. Alle Sub-Marken teilen dieselben Neutraltoene und das goldene Primaer.',
  s02_global: 'Globale Grundlage',
  s03_label: '// 03 Typografie', s03_title: 'Schriftsystem',
  s03_sub: 'Vier Schriftfamilien erfuellen verschiedene Rollen im Oekosystem. Jede Sub-Marke verwendet eine bestimmte Kombination.',
  s04_label: '// 04 Domain-Audit', s04_title: 'Aktueller Stand',
  s04_sub: 'Momentaufnahme aller 6 LABS67-Domains vom 23. Maerz 2026. Jede Domain wurde auf Designkonsistenz, Sprachunterstuetzung und Standardkonformitaet analysiert.',
  s05_label: '// 05 Sprachsystem', s05_title: 'Standard: 11 Sprachen',
  s05_sub: 'ALLE LABS67-Domains muessen 11 Sprachen unterstuetzen. Belarussisch ist die Standardsprache. Spezielle Flaggenregeln fuer BY und RU.',
  s06_label: '// 06 UI-Komponenten', s06_title: 'Komponentenspezifikationen',
  s06_sub: 'Standard-UI-Komponentenspezifikationen fuer Entwickler. Alle Masse in Pixeln, alle Dauern in Millisekunden.',
  s07_label: '// 07 Gefundene Inkonsistenzen', s07_title: 'Audit-Probleme',
  s07_sub: 'Beim Domain-Audit entdeckte Probleme, die fuer die Markenkonsistenz behoben werden muessen.',
  issue_langs_title: 'Sprachanzahl-Abweichung', issue_langs_desc: 'Alle Domains haben jetzt vollstaendige Sprachabdeckung. svyatlitsa: 11 Sprachen. academi67/trade/franchise: je 12 Sprachen.',
  issue_chat_title: 'svyatlitsa.com ohne Chat-Widget', issue_chat_desc: 'Chat-Widget wurde zu svyatlitsa.com hinzugefuegt. Patienten koennen jetzt direkt von der Klinikwebsite mit SCYRA AI interagieren.',
  s08_label: '// 08 Entwicklerrichtlinien', s08_title: 'Implementierungsregeln',
  s08_sub: 'Verbindliche Regeln fuer jeden Entwickler, der an LABS67-Oekosystem-Websites arbeitet. Befolgen Sie diese vor jeder Aenderung.',
  footer_version: 'Brand Book v1.0 // Erstellt 2026-03-23',
  footer_copy: '&copy; 2026 LABS67 Konzern // Vertraulich'
},
fr: {
  nav_arch: 'Architecture', nav_colors: 'Couleurs', nav_typo: 'Typographie', nav_domains: 'Domaines',
  nav_langs: 'Langues', nav_components: 'Composants', nav_issues: 'Problemes', nav_guidelines: 'Directives',
  hero_eyebrow: '// Brand Book du groupe LABS67',
  hero_title: 'Systeme<br><em>de marque</em>',
  hero_sub: 'Standards de design complets, systemes de couleurs, regles typographiques, specifications de composants et directives pour tous les domaines du groupe LABS67. Pour les developpeurs, designers et partenaires.',
  hero_domains: 'Domaines', hero_subbrands: 'Sous-marques', hero_languages: 'Langues', hero_fonts: 'Familles de polices', hero_system: 'Systeme',
  toc_label: '// Sommaire', toc_title: 'Structure du Brand Book',
  toc_arch: 'Architecture de marque', toc_arch_desc: 'Marque parente, sous-marques, hierarchie et relations',
  toc_colors: 'Systeme de couleurs', toc_colors_desc: 'Palettes primaires, secondaires et d\'accent par marque',
  toc_typo: 'Typographie', toc_typo_desc: 'Familles de polices, tailles, graisses, regles d\'utilisation',
  toc_domains: 'Audit des domaines', toc_domains_desc: 'Etat actuel des 6 domaines',
  toc_langs: 'Systeme linguistique', toc_langs_desc: '11 langues, drapeaux, standards i18n',
  toc_components: 'Composants UI', toc_components_desc: 'Boutons, formulaires, cartes, specifications de navigation',
  toc_issues: 'Incoherences', toc_issues_desc: 'Problemes trouves et corrections requises',
  toc_guidelines: 'Directives developpeurs', toc_guidelines_desc: 'Regles pour les developpeurs lors des modifications',
  s01_label: '// 01 Architecture de marque', s01_title: 'Structure du groupe',
  s01_sub: 'LABS67 est un groupe technologique (societe holding) avec 5 sous-marques operationnelles. Chaque sous-marque a sa propre identite visuelle mais doit suivre le systeme parent.',
  arch_parent_desc: 'Groupe technologique // Marque parente',
  arch_svt: 'Dentisterie esthetique', arch_scyra: 'Systeme Edge AI', arch_academi: 'Formation clinique',
  arch_trade: 'Produits MedTech', arch_franchise: 'Expansion & Partenaires',
  s02_label: '// 02 Systeme de couleurs', s02_title: 'Palette de couleurs',
  s02_sub: 'Le systeme de couleurs LABS67 definit une base partagee avec des couleurs d\'accent specifiques a chaque marque. Toutes les sous-marques partagent les memes neutres et le dore primaire.',
  s02_global: 'Base globale',
  s03_label: '// 03 Typographie', s03_title: 'Systeme de polices',
  s03_sub: 'Quatre familles de polices remplissent differents roles dans l\'ecosysteme. Chaque sous-marque utilise une combinaison specifique.',
  s04_label: '// 04 Audit des domaines', s04_title: 'Etat actuel',
  s04_sub: 'Instantane des 6 domaines LABS67 au 23 mars 2026. Chaque domaine analyse pour la coherence du design, le support linguistique et la conformite aux standards.',
  s05_label: '// 05 Systeme linguistique', s05_title: 'Standard 11 langues',
  s05_sub: 'TOUS les domaines LABS67 doivent supporter 11 langues. Le bielorusse est la langue par defaut. Regles speciales de drapeaux pour BY et RU.',
  s06_label: '// 06 Composants UI', s06_title: 'Specifications des composants',
  s06_sub: 'Specifications standard des composants UI pour les developpeurs. Toutes les mesures en pixels, toutes les durees en millisecondes.',
  s07_label: '// 07 Incoherences trouvees', s07_title: 'Problemes d\'audit',
  s07_sub: 'Problemes decouverts lors de l\'audit des domaines qui doivent etre corriges pour la coherence de la marque.',
  issue_langs_title: 'Ecart du nombre de langues', issue_langs_desc: 'Tous les domaines ont maintenant une couverture linguistique complete. svyatlitsa: 11 langues. academi67/trade/franchise: 12 langues chacun.',
  issue_chat_title: 'svyatlitsa.com sans widget de chat', issue_chat_desc: 'Le widget de chat a ete ajoute a svyatlitsa.com. Les patients peuvent maintenant interagir avec SCYRA AI directement depuis le site de la clinique.',
  s08_label: '// 08 Directives developpeurs', s08_title: 'Regles d\'implementation',
  s08_sub: 'Regles obligatoires pour tout developpeur travaillant sur les sites de l\'ecosysteme LABS67. Suivez-les avant toute modification.',
  footer_version: 'Brand Book v1.0 // Genere le 2026-03-23',
  footer_copy: '&copy; 2026 Groupe LABS67 // Confidentiel'
},
es: {
  nav_arch: 'Arquitectura', nav_colors: 'Colores', nav_typo: 'Tipografia', nav_domains: 'Dominios',
  nav_langs: 'Idiomas', nav_components: 'Componentes', nav_issues: 'Problemas', nav_guidelines: 'Directrices',
  hero_eyebrow: '// Brand Book del grupo LABS67',
  hero_title: 'Sistema<br><em>de marca</em>',
  hero_sub: 'Estandares de diseno completos, sistemas de color, reglas tipograficas, especificaciones de componentes y directrices para todos los dominios del grupo LABS67. Para desarrolladores, disenadores y socios.',
  hero_domains: 'Dominios', hero_subbrands: 'Sub-marcas', hero_languages: 'Idiomas', hero_fonts: 'Familias tipograficas', hero_system: 'Sistema',
  toc_label: '// Contenido', toc_title: 'Estructura del Brand Book',
  toc_arch: 'Arquitectura de marca', toc_arch_desc: 'Marca principal, sub-marcas, jerarquia y relaciones',
  toc_colors: 'Sistema de colores', toc_colors_desc: 'Paletas primarias, secundarias y de acento por marca',
  toc_typo: 'Tipografia', toc_typo_desc: 'Familias tipograficas, tamanos, pesos, reglas de uso',
  toc_domains: 'Auditoria de dominios', toc_domains_desc: 'Estado actual de los 6 dominios',
  toc_langs: 'Sistema de idiomas', toc_langs_desc: '11 idiomas, banderas, estandares i18n',
  toc_components: 'Componentes UI', toc_components_desc: 'Botones, formularios, tarjetas, especificaciones de navegacion',
  toc_issues: 'Inconsistencias', toc_issues_desc: 'Problemas encontrados y correcciones necesarias',
  toc_guidelines: 'Directrices para desarrolladores', toc_guidelines_desc: 'Reglas para desarrolladores al implementar cambios',
  s01_label: '// 01 Arquitectura de marca', s01_title: 'Estructura del grupo',
  s01_sub: 'LABS67 es un grupo tecnologico (sociedad holding) con 5 sub-marcas operativas. Cada sub-marca tiene su propia identidad visual pero debe seguir el sistema principal.',
  arch_parent_desc: 'Grupo tecnologico // Marca principal',
  arch_svt: 'Odontologia estetica', arch_scyra: 'Sistema Edge AI', arch_academi: 'Educacion clinica',
  arch_trade: 'Productos MedTech', arch_franchise: 'Escalamiento y socios',
  s02_label: '// 02 Sistema de colores', s02_title: 'Paleta de colores',
  s02_sub: 'El sistema de colores LABS67 define una base compartida con colores de acento especificos para cada marca. Todas las sub-marcas comparten los mismos neutros y el dorado primario.',
  s02_global: 'Base global',
  s03_label: '// 03 Tipografia', s03_title: 'Sistema de fuentes',
  s03_sub: 'Cuatro familias tipograficas cumplen diferentes roles en el ecosistema. Cada sub-marca utiliza una combinacion especifica.',
  s04_label: '// 04 Auditoria de dominios', s04_title: 'Estado actual',
  s04_sub: 'Captura de los 6 dominios LABS67 a fecha del 23 de marzo de 2026. Cada dominio analizado en consistencia de diseno, soporte de idiomas y cumplimiento de estandares.',
  s05_label: '// 05 Sistema de idiomas', s05_title: 'Estandar de 11 idiomas',
  s05_sub: 'TODOS los dominios LABS67 deben soportar 11 idiomas. El bielorruso es el idioma por defecto. Reglas especiales de banderas para BY y RU.',
  s06_label: '// 06 Componentes UI', s06_title: 'Especificaciones de componentes',
  s06_sub: 'Especificaciones estandar de componentes UI para desarrolladores. Todas las medidas en pixeles, todas las duraciones en milisegundos.',
  s07_label: '// 07 Inconsistencias encontradas', s07_title: 'Problemas de auditoria',
  s07_sub: 'Problemas descubiertos durante la auditoria de dominios que deben corregirse para la consistencia de marca.',
  issue_langs_title: 'Discrepancia en cantidad de idiomas', issue_langs_desc: 'Todos los dominios ahora tienen cobertura linguistica completa. svyatlitsa: 11 idiomas. academi67/trade/franchise: 12 idiomas cada uno.',
  issue_chat_title: 'svyatlitsa.com sin widget de chat', issue_chat_desc: 'El widget de chat ha sido agregado a svyatlitsa.com. Los pacientes ahora pueden interactuar con SCYRA AI directamente desde el sitio de la clinica.',
  s08_label: '// 08 Directrices para desarrolladores', s08_title: 'Reglas de implementacion',
  s08_sub: 'Reglas obligatorias para cualquier desarrollador que trabaje en sitios del ecosistema LABS67. Siga estas reglas antes de realizar cualquier cambio.',
  footer_version: 'Brand Book v1.0 // Generado 2026-03-23',
  footer_copy: '&copy; 2026 Grupo LABS67 // Confidencial'
},
it: {
  nav_arch: 'Architettura', nav_colors: 'Colori', nav_typo: 'Tipografia', nav_domains: 'Domini',
  nav_langs: 'Lingue', nav_components: 'Componenti', nav_issues: 'Problemi', nav_guidelines: 'Linee guida',
  hero_eyebrow: '// Brand Book del gruppo LABS67',
  hero_title: 'Sistema<br><em>di brand</em>',
  hero_sub: 'Standard di design completi, sistemi cromatici, regole tipografiche, specifiche dei componenti e linee guida per tutti i domini del gruppo LABS67. Per sviluppatori, designer e partner.',
  hero_domains: 'Domini', hero_subbrands: 'Sub-brand', hero_languages: 'Lingue', hero_fonts: 'Famiglie di font', hero_system: 'Sistema',
  toc_label: '// Indice', toc_title: 'Struttura del Brand Book',
  toc_arch: 'Architettura del brand', toc_arch_desc: 'Brand principale, sub-brand, gerarchia e relazioni',
  toc_colors: 'Sistema cromatico', toc_colors_desc: 'Palette primarie, secondarie e di accento per brand',
  toc_typo: 'Tipografia', toc_typo_desc: 'Famiglie di font, dimensioni, pesi, regole d\'uso',
  toc_domains: 'Audit dei domini', toc_domains_desc: 'Stato attuale di tutti i 6 domini',
  toc_langs: 'Sistema linguistico', toc_langs_desc: '11 lingue, bandiere, standard i18n',
  toc_components: 'Componenti UI', toc_components_desc: 'Pulsanti, moduli, schede, specifiche di navigazione',
  toc_issues: 'Incongruenze', toc_issues_desc: 'Problemi trovati e correzioni necessarie',
  toc_guidelines: 'Linee guida per sviluppatori', toc_guidelines_desc: 'Regole per gli sviluppatori nell\'implementazione delle modifiche',
  s01_label: '// 01 Architettura del brand', s01_title: 'Struttura del gruppo',
  s01_sub: 'LABS67 e un gruppo tecnologico (holding) con 5 sub-brand operativi. Ogni sub-brand ha la propria identita visiva ma deve seguire il sistema principale.',
  arch_parent_desc: 'Gruppo tecnologico // Brand principale',
  arch_svt: 'Odontoiatria estetica', arch_scyra: 'Sistema Edge AI', arch_academi: 'Formazione clinica',
  arch_trade: 'Prodotti MedTech', arch_franchise: 'Scalabilita e partner',
  s02_label: '// 02 Sistema cromatico', s02_title: 'Palette dei colori',
  s02_sub: 'Il sistema cromatico LABS67 definisce una base condivisa con colori di accento specifici per brand. Tutti i sub-brand condividono gli stessi toni neutri e il dorato primario.',
  s02_global: 'Base globale',
  s03_label: '// 03 Tipografia', s03_title: 'Sistema di font',
  s03_sub: 'Quattro famiglie di font svolgono ruoli diversi nell\'ecosistema. Ogni sub-brand utilizza una combinazione specifica.',
  s04_label: '// 04 Audit dei domini', s04_title: 'Stato attuale',
  s04_sub: 'Istantanea di tutti i 6 domini LABS67 al 23 marzo 2026. Ogni dominio analizzato per coerenza del design, supporto linguistico e conformita agli standard.',
  s05_label: '// 05 Sistema linguistico', s05_title: 'Standard 11 lingue',
  s05_sub: 'TUTTI i domini LABS67 devono supportare 11 lingue. Il bielorusso e la lingua predefinita. Regole speciali per le bandiere BY e RU.',
  s06_label: '// 06 Componenti UI', s06_title: 'Specifiche dei componenti',
  s06_sub: 'Specifiche standard dei componenti UI per sviluppatori. Tutte le misure in pixel, tutte le durate in millisecondi.',
  s07_label: '// 07 Incongruenze trovate', s07_title: 'Problemi dell\'audit',
  s07_sub: 'Problemi scoperti durante l\'audit dei domini che devono essere corretti per la coerenza del brand.',
  issue_langs_title: 'Discrepanza nel numero di lingue', issue_langs_desc: 'Tutti i domini ora hanno copertura linguistica completa. svyatlitsa: 11 lingue. academi67/trade/franchise: 12 lingue ciascuno.',
  issue_chat_title: 'svyatlitsa.com senza widget chat', issue_chat_desc: 'Il widget chat e stato aggiunto a svyatlitsa.com. I pazienti possono ora interagire con SCYRA AI direttamente dal sito della clinica.',
  s08_label: '// 08 Linee guida per sviluppatori', s08_title: 'Regole di implementazione',
  s08_sub: 'Regole obbligatorie per qualsiasi sviluppatore che lavori sui siti dell\'ecosistema LABS67. Segui queste regole prima di apportare qualsiasi modifica.',
  footer_version: 'Brand Book v1.0 // Generato il 2026-03-23',
  footer_copy: '&copy; 2026 Gruppo LABS67 // Riservato'
},
pt: {
  nav_arch: 'Arquitetura', nav_colors: 'Cores', nav_typo: 'Tipografia', nav_domains: 'Dominios',
  nav_langs: 'Idiomas', nav_components: 'Componentes', nav_issues: 'Problemas', nav_guidelines: 'Diretrizes',
  hero_eyebrow: '// Brand Book do grupo LABS67',
  hero_title: 'Sistema<br><em>de marca</em>',
  hero_sub: 'Padroes completos de design, sistemas de cores, regras tipograficas, especificacoes de componentes e diretrizes para todos os dominios do grupo LABS67. Para desenvolvedores, designers e parceiros.',
  hero_domains: 'Dominios', hero_subbrands: 'Sub-marcas', hero_languages: 'Idiomas', hero_fonts: 'Familias de fontes', hero_system: 'Sistema',
  toc_label: '// Conteudo', toc_title: 'Estrutura do Brand Book',
  toc_arch: 'Arquitetura de marca', toc_arch_desc: 'Marca principal, sub-marcas, hierarquia e relacoes',
  toc_colors: 'Sistema de cores', toc_colors_desc: 'Paletas primarias, secundarias e de destaque por marca',
  toc_typo: 'Tipografia', toc_typo_desc: 'Familias de fontes, tamanhos, pesos, regras de uso',
  toc_domains: 'Auditoria de dominios', toc_domains_desc: 'Estado atual de todos os 6 dominios',
  toc_langs: 'Sistema de idiomas', toc_langs_desc: '11 idiomas, bandeiras, padroes i18n',
  toc_components: 'Componentes UI', toc_components_desc: 'Botoes, formularios, cartoes, especificacoes de navegacao',
  toc_issues: 'Inconsistencias', toc_issues_desc: 'Problemas encontrados e correcoes necessarias',
  toc_guidelines: 'Diretrizes para desenvolvedores', toc_guidelines_desc: 'Regras para desenvolvedores ao implementar mudancas',
  s01_label: '// 01 Arquitetura de marca', s01_title: 'Estrutura do grupo',
  s01_sub: 'LABS67 e um grupo tecnologico (holding) com 5 sub-marcas operacionais. Cada sub-marca tem sua propria identidade visual, mas deve seguir o sistema principal.',
  arch_parent_desc: 'Grupo tecnologico // Marca principal',
  arch_svt: 'Odontologia estetica', arch_scyra: 'Sistema Edge AI', arch_academi: 'Educacao clinica',
  arch_trade: 'Produtos MedTech', arch_franchise: 'Escalabilidade e parceiros',
  s02_label: '// 02 Sistema de cores', s02_title: 'Paleta de cores',
  s02_sub: 'O sistema de cores LABS67 define uma base compartilhada com cores de destaque especificas para cada marca. Todas as sub-marcas compartilham os mesmos tons neutros e o dourado primario.',
  s02_global: 'Base global',
  s03_label: '// 03 Tipografia', s03_title: 'Sistema de fontes',
  s03_sub: 'Quatro familias de fontes desempenham diferentes papeis no ecossistema. Cada sub-marca utiliza uma combinacao especifica.',
  s04_label: '// 04 Auditoria de dominios', s04_title: 'Estado atual',
  s04_sub: 'Captura de todos os 6 dominios LABS67 em 23 de marco de 2026. Cada dominio analisado quanto a consistencia de design, suporte de idiomas e conformidade com padroes.',
  s05_label: '// 05 Sistema de idiomas', s05_title: 'Padrao de 11 idiomas',
  s05_sub: 'TODOS os dominios LABS67 devem suportar 11 idiomas. O bielorrusso e o idioma padrao. Regras especiais de bandeiras para BY e RU.',
  s06_label: '// 06 Componentes UI', s06_title: 'Especificacoes de componentes',
  s06_sub: 'Especificacoes padrao de componentes UI para desenvolvedores. Todas as medidas em pixels, todas as duracoes em milissegundos.',
  s07_label: '// 07 Inconsistencias encontradas', s07_title: 'Problemas da auditoria',
  s07_sub: 'Problemas descobertos durante a auditoria de dominios que precisam ser corrigidos para consistencia da marca.',
  issue_langs_title: 'Discrepancia na quantidade de idiomas', issue_langs_desc: 'Todos os dominios agora tem cobertura linguistica completa. svyatlitsa: 11 idiomas. academi67/trade/franchise: 12 idiomas cada.',
  issue_chat_title: 'svyatlitsa.com sem widget de chat', issue_chat_desc: 'O widget de chat foi adicionado ao svyatlitsa.com. Os pacientes agora podem interagir com SCYRA AI diretamente do site da clinica.',
  s08_label: '// 08 Diretrizes para desenvolvedores', s08_title: 'Regras de implementacao',
  s08_sub: 'Regras obrigatorias para qualquer desenvolvedor que trabalhe em sites do ecossistema LABS67. Siga estas regras antes de fazer qualquer alteracao.',
  footer_version: 'Brand Book v1.0 // Gerado em 2026-03-23',
  footer_copy: '&copy; 2026 Grupo LABS67 // Confidencial'
},
ja: {
  nav_arch: 'アーキテクチャ', nav_colors: 'カラー', nav_typo: 'タイポグラフィ', nav_domains: 'ドメイン',
  nav_langs: '言語', nav_components: 'コンポーネント', nav_issues: '課題', nav_guidelines: 'ガイドライン',
  hero_eyebrow: '// LABS67グループ ブランドブック',
  hero_title: 'ブランド<br><em>システム</em>',
  hero_sub: 'LABS67グループの全ドメインに対するデザイン基準、カラーシステム、タイポグラフィルール、コンポーネント仕様、ガイドラインの完全版。開発者、デザイナー、パートナー向け。',
  hero_domains: 'ドメイン', hero_subbrands: 'サブブランド', hero_languages: '言語', hero_fonts: 'フォントファミリー', hero_system: 'システム',
  toc_label: '// 目次', toc_title: 'ブランドブック構成',
  toc_arch: 'ブランドアーキテクチャ', toc_arch_desc: '親ブランド、サブブランド、階層構造と関係性',
  toc_colors: 'カラーシステム', toc_colors_desc: 'ブランド別のプライマリ、セカンダリ、アクセントパレット',
  toc_typo: 'タイポグラフィ', toc_typo_desc: 'フォントファミリー、サイズ、ウェイト、使用ルール',
  toc_domains: 'ドメイン監査', toc_domains_desc: '全6ドメインの現状',
  toc_langs: '言語システム', toc_langs_desc: '11言語、国旗、i18n基準',
  toc_components: 'UIコンポーネント', toc_components_desc: 'ボタン、フォーム、カード、ナビゲーション仕様',
  toc_issues: '不整合', toc_issues_desc: '発見された問題と必要な修正',
  toc_guidelines: '開発者ガイドライン', toc_guidelines_desc: '変更を実装する際の開発者向けルール',
  s01_label: '// 01 ブランドアーキテクチャ', s01_title: 'グループ構造',
  s01_sub: 'LABS67は5つの運営サブブランドを持つテクノロジーコンツェルン（持株会社）です。各サブブランドは独自のビジュアルアイデンティティを持ちますが、親システムに従う必要があります。',
  arch_parent_desc: 'テクノロジーコンツェルン // 親ブランド',
  arch_svt: '審美歯科', arch_scyra: 'Edge AIシステム', arch_academi: '臨床教育',
  arch_trade: 'MedTech製品', arch_franchise: 'スケーリングとパートナー',
  s02_label: '// 02 カラーシステム', s02_title: 'カラーパレット',
  s02_sub: 'LABS67のカラーシステムは、ブランド固有のアクセントカラーを持つ共有基盤を定義します。すべてのサブブランドは同じニュートラルトーンとゴールドプライマリを共有します。',
  s02_global: 'グローバル基盤',
  s03_label: '// 03 タイポグラフィ', s03_title: 'フォントシステム',
  s03_sub: '4つのフォントファミリーがエコシステム内で異なる役割を果たします。各サブブランドは特定の組み合わせを使用します。',
  s04_label: '// 04 ドメイン監査', s04_title: '現状',
  s04_sub: '2026年3月23日時点のLABS67全6ドメインのスナップショット。各ドメインのデザイン整合性、言語サポート、標準準拠を分析。',
  s05_label: '// 05 言語システム', s05_title: '11言語標準',
  s05_sub: 'すべてのLABS67ドメインは11言語をサポートする必要があります。ベラルーシ語がデフォルト言語です。BYとRUには特別な国旗ルールが適用されます。',
  s06_label: '// 06 UIコンポーネント', s06_title: 'コンポーネント仕様',
  s06_sub: '開発者向け標準UIコンポーネント仕様。すべての測定値はピクセル単位、すべての時間はミリ秒単位。',
  s07_label: '// 07 発見された不整合', s07_title: '監査の課題',
  s07_sub: 'ドメイン監査中に発見された、ブランドの整合性のために修正が必要な問題。',
  issue_langs_title: '言語数の不一致', issue_langs_desc: 'すべてのドメインが完全な言語カバレッジを達成。svyatlitsa: 11言語。academi67/trade/franchise: 各12言語。',
  issue_chat_title: 'svyatlitsa.comにチャットウィジェットなし', issue_chat_desc: 'svyatlitsa.comにチャットウィジェットが追加されました。患者がクリニックのウェブサイトから直接SCYRA AIと対話できるようになりました。',
  s08_label: '// 08 開発者ガイドライン', s08_title: '実装ルール',
  s08_sub: 'LABS67エコシステムサイトで作業するすべての開発者の必須ルール。変更を加える前にこれらに従ってください。',
  footer_version: 'ブランドブック v1.0 // 生成日 2026-03-23',
  footer_copy: '&copy; 2026 LABS67コンツェルン // 機密'
},
ko: {
  nav_arch: '아키텍처', nav_colors: '색상', nav_typo: '타이포그래피', nav_domains: '도메인',
  nav_langs: '언어', nav_components: '컴포넌트', nav_issues: '문제점', nav_guidelines: '가이드라인',
  hero_eyebrow: '// LABS67 그룹 브랜드 북',
  hero_title: '브랜드<br><em>시스템</em>',
  hero_sub: 'LABS67 그룹 모든 도메인에 대한 완전한 디자인 표준, 색상 시스템, 타이포그래피 규칙, 컴포넌트 사양 및 가이드라인. 개발자, 디자이너 및 파트너를 위한 것입니다.',
  hero_domains: '도메인', hero_subbrands: '서브 브랜드', hero_languages: '언어', hero_fonts: '폰트 패밀리', hero_system: '시스템',
  toc_label: '// 목차', toc_title: '브랜드 북 구조',
  toc_arch: '브랜드 아키텍처', toc_arch_desc: '모 브랜드, 서브 브랜드, 계층 구조 및 관계',
  toc_colors: '색상 시스템', toc_colors_desc: '브랜드별 기본, 보조, 강조 팔레트',
  toc_typo: '타이포그래피', toc_typo_desc: '폰트 패밀리, 크기, 두께, 사용 규칙',
  toc_domains: '도메인 감사', toc_domains_desc: '전체 6개 도메인의 현재 상태',
  toc_langs: '언어 시스템', toc_langs_desc: '11개 언어, 국기, i18n 표준',
  toc_components: 'UI 컴포넌트', toc_components_desc: '버튼, 폼, 카드, 네비게이션 사양',
  toc_issues: '불일치', toc_issues_desc: '발견된 문제점 및 필요한 수정 사항',
  toc_guidelines: '개발자 가이드라인', toc_guidelines_desc: '변경 사항 구현 시 개발자를 위한 규칙',
  s01_label: '// 01 브랜드 아키텍처', s01_title: '그룹 구조',
  s01_sub: 'LABS67은 5개의 운영 서브 브랜드를 보유한 기술 콘체른(지주회사)입니다. 각 서브 브랜드는 고유한 시각적 정체성을 가지지만 상위 시스템을 따라야 합니다.',
  arch_parent_desc: '기술 콘체른 // 모 브랜드',
  arch_svt: '심미 치과', arch_scyra: 'Edge AI 시스템', arch_academi: '임상 교육',
  arch_trade: 'MedTech 제품', arch_franchise: '스케일링 및 파트너',
  s02_label: '// 02 색상 시스템', s02_title: '색상 팔레트',
  s02_sub: 'LABS67 색상 시스템은 브랜드별 강조 색상과 함께 공유 기반을 정의합니다. 모든 서브 브랜드는 동일한 중성 톤과 골드 기본색을 공유합니다.',
  s02_global: '글로벌 기반',
  s03_label: '// 03 타이포그래피', s03_title: '폰트 시스템',
  s03_sub: '4개의 폰트 패밀리가 생태계에서 서로 다른 역할을 수행합니다. 각 서브 브랜드는 특정 조합을 사용합니다.',
  s04_label: '// 04 도메인 감사', s04_title: '현재 상태',
  s04_sub: '2026년 3월 23일 기준 LABS67 전체 6개 도메인의 스냅샷. 각 도메인의 디자인 일관성, 언어 지원 및 표준 준수 분석.',
  s05_label: '// 05 언어 시스템', s05_title: '11개 언어 표준',
  s05_sub: '모든 LABS67 도메인은 11개 언어를 지원해야 합니다. 벨라루스어가 기본 언어입니다. BY 및 RU에 대한 특별 국기 규칙이 적용됩니다.',
  s06_label: '// 06 UI 컴포넌트', s06_title: '컴포넌트 사양',
  s06_sub: '개발자를 위한 표준 UI 컴포넌트 사양. 모든 측정값은 픽셀 단위, 모든 지속 시간은 밀리초 단위.',
  s07_label: '// 07 발견된 불일치', s07_title: '감사 문제점',
  s07_sub: '도메인 감사 중 발견된 브랜드 일관성을 위해 수정이 필요한 문제점.',
  issue_langs_title: '언어 수 불일치', issue_langs_desc: '모든 도메인이 완전한 언어 커버리지를 달성했습니다. svyatlitsa: 11개 언어. academi67/trade/franchise: 각 12개 언어.',
  issue_chat_title: 'svyatlitsa.com 채팅 위젯 없음', issue_chat_desc: 'svyatlitsa.com에 채팅 위젯이 추가되었습니다. 환자가 이제 클리닉 웹사이트에서 직접 SCYRA AI와 상호작용할 수 있습니다.',
  s08_label: '// 08 개발자 가이드라인', s08_title: '구현 규칙',
  s08_sub: 'LABS67 생태계 사이트에서 작업하는 모든 개발자의 필수 규칙. 변경 사항을 적용하기 전에 이 규칙을 따르십시오.',
  footer_version: '브랜드 북 v1.0 // 생성일 2026-03-23',
  footer_copy: '&copy; 2026 LABS67 콘체른 // 기밀'
}
};
